<a href="https://colab.research.google.com/github/KarlyHdzC/Mineria_de_datos/blob/main/Gaming_Laptops_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de Datos - Universidad Anáhuac
## Introducción a Python - USO DE CSV Y PANDAS
**Karla Beatriz Hernández Castro*

Gaming Laptops 2026

Kaggle: https://www.kaggle.com/datasets/kanchana1990/gaming-laptops-2026

# Trabajando con archivos CSV

In [3]:
# Importar pandas
import pandas as pd

In [1]:
# Montamos Google Drive para acceder a los archivos almancenados en la unidad

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# Guardamos el archivo dentro de un dataframe de Pandas

file_path = "/content/drive/MyDrive/Colab Notebooks/Mineria de datos/gaming_laptops_2026_q1.csv"

laptops_df = pd.read_csv(file_path, encoding='latin1', delimiter=',')

In [5]:
# Muestra los primeros 5 registros por defecto
# aunque se le puede pasar un valor a head()

laptops_df.head()

,title,brand,price,list_price,discount_pct,price_currency,stars,reviews_count,breadCrumbs,description
0,Apple 2025 MacBook Air 13-inch Laptop with M4 ...,Apple,949.00,999.00,5.01,$,4.8,5991,NaN,NaN
1,Apple 2025 MacBook Pro Laptop with M5 chip wit...,Apple,1449.00,1599.00,9.38,$,4.7,1217,NaN,NaN
2,Lenovo Legion Pro 7i â AI-Powered Gaming Lap...,Lenovo,2004.89,2149.99,6.75,$,4.3,139,Electronics > Computers & Accessories > Comput...,The Lenovo Legion Pro 7i is designed for eSpor...
3,LG 45GX950A-B 45-inch Ultragear 5K2K WUHD (512...,LG,1486.99,1999.99,25.65,$,4.3,323,Electronics > Computers & Accessories > Monitors,Unleash unparalleled gaming prowess with the w...
4,acer Nitro V Gaming Laptop | Intel Core i7-136...,acer,949.99,NaN,0.00,$,4.6,205,Electronics > Computers & Accessories > Comput...,Live For Victory: Elevate your gaming adventur...

In [7]:
# Ahora vamos a ver todas las columnas en el DF

laptops_df.columns

Index(['title', 'brand', 'price', 'list_price', 'discount_pct',
       'price_currency', 'stars', 'reviews_count', 'breadCrumbs',
       'description'],
      dtype='object')

In [8]:
# Mostramos la estructura del DF en (filas, columnas)

laptops_df.shape

(614, 10)

In [9]:
laptops_df.dtypes

title              object
brand              object
price             float64
list_price        float64
discount_pct      float64
price_currency     object
stars             float64
reviews_count       int64
breadCrumbs        object
description        object
dtype: object

In [10]:
# Los datos tipo object contienen números y letras
# esto no es de Pyhton, es de Pandas.

laptops_df['brand']

0          Apple
1          Apple
2         Lenovo
3             LG
4           acer
         ...
609       Lenovo
610         acer
611    Microsoft
612         NIMO
613         ASUS
Name: brand, Length: 614, dtype: object

In [11]:
# Vamos a mostrar los últimos 3 registros
# Para ello usaremos tail()

laptops_df.tail(3)

,title,brand,price,list_price,discount_pct,price_currency,stars,reviews_count,breadCrumbs,description
611,"Microsoft Surface Pro 13"" 3K 120Hz Touchscreen...",Microsoft,1049.99,1199.99,12.5,$,NaN,0,Electronics > Computers & Accessories > Comput...,NaN
612,NIMO 17.3 Gaming-Laptop Ryzen 9 8945HS (Beat i...,NIMO,949.98,NaN,0.0,$,4.7,18,Electronics > Computers & Accessories > Comput...,NaN
613,"ASUS ROG Zephyrus G14 AI Gaming Laptop 14.0"" 1...",ASUS,2699.99,NaN,0.0,$,5.0,1,Electronics > Computers & Accessories > Comput...,NaN

In [16]:
# Ahora vamos a mostrar solo los últimos 3 registros de ventas

last_prices = laptops_df.tail(3)['price']

last_prices

611    1049.99
612     949.98
613    2699.99
Name: price, dtype: float64

In [17]:
# Aquí se mantiene el index de la tabla original
# La tabla original está en sales_df

print(last_prices)

611    1049.99
612     949.98
613    2699.99
Name: price, dtype: float64

In [18]:
# Vamos a resetear el index de este data_frame para evitar errores
# Esto si queremos despues iterar sobre este data_frame

last_prices = last_prices.reset_index(drop=True)

print(last_prices)

0    1049.99
1     949.98
2    2699.99
Name: price, dtype: float64

In [19]:
# Veamos la estructura de last_prices

last_prices.shape # Ojo, no tenemos columna

(3,)

In [21]:
last_prices = laptops_df.tail(3)[['price']]
last_prices = last_prices.reset_index(drop=True)
last_prices.shape

(3, 1)

La diferencia entre usar `['COLUMNA']` y `[['COLUMNA']]` es que en la primera nos va a pasar una *serie*, algo muy parecido a una lista o un arreglo. Mientras que en el segundo formato vamos a pasar un data frame, que incluye la columna y los registros.

In [23]:
# Vamos a traer las 5 primeras computadoras con sus precios
first_laptops_status = laptops_df.head(5)[['brand', 'price']]

first_laptops_status

    brand    price
0   Apple   949.00
1   Apple  1449.00
2  Lenovo  2004.89
3      LG  1486.99
4    acer   949.99

In [24]:
# Vamos a traer todas las ventas y el estatus

all_laptops_price = laptops_df[['brand', 'price']]

all_laptops_price

         brand    price
0        Apple   949.00
1        Apple  1449.00
2       Lenovo  2004.89
3           LG  1486.99
4         acer   949.99
..         ...      ...
609     Lenovo  3799.00
610       acer  1349.00
611  Microsoft  1049.99
612       NIMO   949.98
613       ASUS  2699.99

[614 rows x 2 columns]

In [25]:
# Filtramos las laptops con un precio superior a 1200 dólares
high_price_laptops = laptops_df[laptops_df['price'] > 1200]

high_price_laptops

,title,brand,price,list_price,discount_pct,price_currency,stars,reviews_count,breadCrumbs,description
1,Apple 2025 MacBook Pro Laptop with M5 chip wit...,Apple,1449.00,1599.00,9.38,$,4.7,1217,NaN,NaN
2,Lenovo Legion Pro 7i â AI-Powered Gaming Lap...,Lenovo,2004.89,2149.99,6.75,$,4.3,139,Electronics > Computers & Accessories > Comput...,The Lenovo Legion Pro 7i is designed for eSpor...
3,LG 45GX950A-B 45-inch Ultragear 5K2K WUHD (512...,LG,1486.99,1999.99,25.65,$,4.3,323,Electronics > Computers & Accessories > Monitors,Unleash unparalleled gaming prowess with the w...
5,"msi Codex Z2 Gaming Desktop: AMD R7-8700F, GeF...",msi,1888.08,NaN,0.00,$,4.2,177,Electronics > Computers & Accessories > Comput...,"MSI Codex Z2 Gaming Desktop: AMD R7-8700F, GeF..."
6,Alienware 16 Aurora Laptop AC16250-16-inch 16:...,Alienware,1278.49,1399.99,8.68,$,4.2,87,Electronics > Computers & Accessories > Comput...,Alienware 16 Aurora Gaming Laptop. Pure perfor...
...,...,...,...,...,...,...,...,...,...,...
605,"Lenovo LOQ 17.3"" FHD 165Hz Gaming Laptop, NVID...",Lenovo,1369.00,NaN,0.00,$,4.4,14,Electronics > Computers & Accessories > Comput...,"Lenovo LOQ 17.3"" FHD 165Hz Gaming Laptop, Inte..."
608,"ASUS Vivobook 16"" WQXGA+ OLED 120Hz Laptop, In...",ASUS,1339.00,NaN,0.00,$,4.3,6,Electronics > Computers & Accessories > Comput...,"ASUS Vivobook 16"" WQXGA+ OLED 120Hz Laptop"
609,"Lenovo ThinkPad T1g Gen 8, AI Laptop, Intel Ul...",Lenovo,3799.00,NaN,0.00,$,NaN,0,Electronics > Computers & Accessories > Comput...,Disclaim: We specialize in computers with pers...
610,"acer Nitro V 16S Gaming Laptop 16"" WUXGA IPS 1...",acer,1349.00,NaN,0.00,$,4.1,7,Electronics > Computers & Accessories > Comput...,PRODUCT OVERVIEW: Product Details: Microproce...
613,"ASUS ROG Zephyrus G14 AI Gaming Laptop 14.0"" 1...",ASUS,2699.99,NaN,0.00,$,5.0,1,Electronics > Computers & Accessories > Comput...,NaN

`describe()` en pandas es una herramienta extremadamente útil para obtener un resumen estadístico de los datos de un DataFrame o Serie.

### ¿Qué hace `describe()`?
Proporciona estadísticas descriptivas que resumen la tendencia central, la dispersión y la forma de la distribución de los datos de un DataFrame o Serie.

Por defecto, solo funciona con **columnas numéricas**, aunque también puedes aplicarlo a datos categóricos.

---

### ¿Qué incluye el resumen?
Para datos **numéricos**, incluye:
1. **count**: Número de valores no nulos.
2. **mean**: Media aritmética.
3. **std**: Desviación estándar.
4. **min**: Valor mínimo.
5. **25%**, **50% (mediana)**, **75%**: Cuartiles.
6. **max**: Valor máximo.

Para datos **categóricos** (`include='object'`), incluye:
1. **count**: Número de valores no nulos.
2. **unique**: Número de valores únicos.
3. **top**: Valor más frecuente (moda).
4. **freq**: Frecuencia del valor más frecuente.

In [26]:
laptops_df.describe()

             price   list_price  discount_pct       stars  reviews_count
count   614.000000   115.000000    614.000000  498.000000     614.000000
mean   1651.402948  1747.848174      3.306938    4.413052      97.415309
std     778.558320   651.536081      8.527061    0.544342     432.426914
min     778.000000   899.000000      0.000000    1.000000       0.000000
25%    1034.742500  1266.490000      0.000000    4.200000       1.000000
50%    1448.995000  1599.990000      0.000000    4.400000       9.000000
75%    2003.665000  2124.990000      0.000000    4.800000      38.000000
max    5859.000000  4399.990000     44.800000    5.000000    6382.000000

In [27]:
laptops_df.describe(include="object")

,title,brand,price_currency,breadCrumbs,description
count,614,614,614,602,472
unique,613,39,1,9,434
top,"NIMO Gaming-Laptop, 15.6"" Computer with AMD 8 ...",Lenovo,$,Electronics > Computers & Accessories > Comput...,"Lenovo LOQ 15.6"" FHD 144Hz Gaming Laptop, Inte..."
freq,2,150,614,548,5

In [29]:
# Calcular el precio promedio por marca
average_prices_by_brand = laptops_df.groupby('brand')['price'].mean().sort_values()

# Mostrar las marcas con los precios promedio más bajos (por ejemplo, las 5 más baratas)
display(average_prices_by_brand.head())

brand
SAGAWHALE     879.990000
jumper        964.990000
Beelink       969.000000
INNOCN        999.990000
NIMO         1002.294615
Name: price, dtype: float64

In [30]:
# Seleccionar las marcas más baratas (por ejemplo, las 5 primeras de la lista ordenada)
cheapest_brands = average_prices_by_brand.head(5).index.tolist()

# Filtrar el DataFrame original para incluir solo estas marcas
cheapest_laptops_df = laptops_df[laptops_df['brand'].isin(cheapest_brands)]

display(cheapest_laptops_df.head())

,title,brand,price,list_price,discount_pct,price_currency,stars,reviews_count,breadCrumbs,description
50,INNOCN 40 Inch 5K 5120 x 2160p Ultrawide Monit...,INNOCN,999.99,NaN,0.0,$,4.2,1210,Electronics > Computers & Accessories > Monitors,NaN
59,NIMO 17.3 Gaming-Laptop Ryzen 9 8945HS (Beat i...,NIMO,899.97,1199.99,25.0,$,4.3,28,Electronics > Computers & Accessories > Comput...,NaN
125,"NIMO 15.6"" IPS FHD-Gaming-Laptop, 8 Cores AMD ...",NIMO,999.99,NaN,0.0,$,2.0,2,Electronics > Computers & Accessories > Comput...,NaN
149,"NIMO Gaming-Laptop, 15.6"" Computer with AMD 8 ...",NIMO,1299.99,NaN,0.0,$,3.4,12,Electronics > Computers & Accessories > Comput...,NaN
194,"2026 15.6"" FHD Gaming Laptop: AMD Ryzen 7 6800...",SAGAWHALE,879.99,NaN,0.0,$,5.0,3,Electronics > Computers & Accessories > Comput...,NaN

In [31]:
# Cuantos valores únicos tiene breadCrumbs

laptops_df["breadCrumbs"].unique()

array([nan,
       'Electronics > Computers & Accessories > Computers & Tablets > Laptops > Traditional Laptops',
       'Electronics > Computers & Accessories > Monitors',
       'Electronics > Computers & Accessories > Computers & Tablets > Desktops > Towers',
       'Electronics > Computers & Accessories > Computers & Tablets > Laptops > 2 in 1 Laptops',
       'Electronics > Computers & Accessories > Computers & Tablets',
       'Electronics > Computers & Accessories > Computers & Tablets > Desktops > Minis',
       'Electronics > Computers & Accessories > Computers & Tablets > Tablets',
       'Musical Instruments > Instrument Accessories > General Accessories > Metronomes',
       'Electronics > Computers & Accessories > Computer Components > Internal Components > Fans & Cooling > Graphics Card Fans'],
      dtype=object)

Uso de min() y max()
1. min():
* Encuentra el valor más pequeño en los datos.
2. max():
* Encuentra el valor más grande en los datos.
Ambos métodos pueden aplicarse a datos numéricos y categóricos.

In [33]:
# Operamos sobre max y min de descuento

min_discount = laptops_df["discount_pct"].min()
max_discount = laptops_df["discount_pct"].max()

print("Descuento mínimo", min_discount)
print("Descuento máximo:", max_discount)

Descuento mínimo 0.0
Descuento máximo: 44.8