<a href="https://colab.research.google.com/github/KarlyHdzC/Mineria_de_datos/blob/main/Gaming_Laptops_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de Datos - Universidad Anáhuac
## Introducción a Python - USO DE CSV Y PANDAS
**Karla Beatriz Hernández Castro*

Gaming Laptops 2026

Kaggle: https://www.kaggle.com/datasets/kanchana1990/gaming-laptops-2026

**Objetivo**
Desarrollar la competencia de manipulación de datos mediante el uso de la librería Pandas, aplicando técnicas de carga, limpieza, exploración y filtrado sobre un conjunto de datos de interés personal del alumno.

Instrucciones para el alumno

Selección de Datos: Busca un archivo CSV o Excel de un tema que te apasione (deportes, finanzas, videojuegos, clima, etc.). Puedes usar sitios como Kaggle o Google Dataset Search.

Preparación: Crea una copia de la libreta de ejemplo en tu propio Google Drive.

Desarrollo: Completa las secciones de código detalladas a continuación, asegurándote de comentar qué estás haciendo en cada celda de texto.

Entrega: Comparte el enlace de tu libreta de Colab con permisos de lectura.

# Trabajando con archivos CSV

In [1]:
# Importar pandas
import pandas as pd

In [2]:
# Montamos Google Drive para acceder a los archivos almancenados en la unidad

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

1) Carga de Datos: Importar la librería y cargar el archivo usando pd.read_csv() o pd.read_excel().

In [4]:
# Guardamos el archivo dentro de un dataframe de Pandas

file_path = "/content/drive/MyDrive/Colab Notebooks/Mineria de datos/gaming_laptops_2026_q1.csv"

laptops_df = pd.read_csv(file_path, encoding='latin1', delimiter=',')

2. Exploración Inicial: Uso de funciones como .head(), .info(), .describe() y .shape.

In [5]:
# Muestra los primeros 5 registros por defecto
# aunque se le puede pasar un valor a head()

laptops_df.head()

,title,brand,price,list_price,discount_pct,price_currency,stars,reviews_count,breadCrumbs,description
0,Apple 2025 MacBook Air 13-inch Laptop with M4 ...,Apple,949.00,999.00,5.01,$,4.8,5991,NaN,NaN
1,Apple 2025 MacBook Pro Laptop with M5 chip wit...,Apple,1449.00,1599.00,9.38,$,4.7,1217,NaN,NaN
2,Lenovo Legion Pro 7i â AI-Powered Gaming Lap...,Lenovo,2004.89,2149.99,6.75,$,4.3,139,Electronics > Computers & Accessories > Comput...,The Lenovo Legion Pro 7i is designed for eSpor...
3,LG 45GX950A-B 45-inch Ultragear 5K2K WUHD (512...,LG,1486.99,1999.99,25.65,$,4.3,323,Electronics > Computers & Accessories > Monitors,Unleash unparalleled gaming prowess with the w...
4,acer Nitro V Gaming Laptop | Intel Core i7-136...,acer,949.99,NaN,0.00,$,4.6,205,Electronics > Computers & Accessories > Comput...,Live For Victory: Elevate your gaming adventur...

In [6]:
# Ahora vamos a ver todas las columnas en el DF

laptops_df.columns

Index(['title', 'brand', 'price', 'list_price', 'discount_pct',
       'price_currency', 'stars', 'reviews_count', 'breadCrumbs',
       'description'],
      dtype='object')

In [7]:
# Mostramos la estructura del DF en (filas, columnas)

laptops_df.shape

(614, 10)

In [8]:
laptops_df.dtypes

title              object
brand              object
price             float64
list_price        float64
discount_pct      float64
price_currency     object
stars             float64
reviews_count       int64
breadCrumbs        object
description        object
dtype: object

In [9]:
# Los datos tipo object contienen números y letras
# esto no es de Pyhton, es de Pandas.

laptops_df['brand']

0          Apple
1          Apple
2         Lenovo
3             LG
4           acer
         ...
609       Lenovo
610         acer
611    Microsoft
612         NIMO
613         ASUS
Name: brand, Length: 614, dtype: object

In [10]:
# Vamos a mostrar los últimos 3 registros
# Para ello usaremos tail()

laptops_df.tail(3)

,title,brand,price,list_price,discount_pct,price_currency,stars,reviews_count,breadCrumbs,description
611,"Microsoft Surface Pro 13"" 3K 120Hz Touchscreen...",Microsoft,1049.99,1199.99,12.5,$,NaN,0,Electronics > Computers & Accessories > Comput...,NaN
612,NIMO 17.3 Gaming-Laptop Ryzen 9 8945HS (Beat i...,NIMO,949.98,NaN,0.0,$,4.7,18,Electronics > Computers & Accessories > Comput...,NaN
613,"ASUS ROG Zephyrus G14 AI Gaming Laptop 14.0"" 1...",ASUS,2699.99,NaN,0.0,$,5.0,1,Electronics > Computers & Accessories > Comput...,NaN

In [11]:
# Ahora vamos a mostrar solo los últimos 3 registros de ventas

last_prices = laptops_df.tail(3)['price']

last_prices

611    1049.99
612     949.98
613    2699.99
Name: price, dtype: float64

In [12]:
# Aquí se mantiene el index de la tabla original
# La tabla original está en sales_df

print(last_prices)

611    1049.99
612     949.98
613    2699.99
Name: price, dtype: float64

In [13]:
# Vamos a resetear el index de este data_frame para evitar errores
# Esto si queremos despues iterar sobre este data_frame

last_prices = last_prices.reset_index(drop=True)

print(last_prices)

0    1049.99
1     949.98
2    2699.99
Name: price, dtype: float64

In [14]:
# Veamos la estructura de last_prices

last_prices.shape # Ojo, no tenemos columna

(3,)

In [15]:
last_prices = laptops_df.tail(3)[['price']]
last_prices = last_prices.reset_index(drop=True)
last_prices.shape

(3, 1)

La diferencia entre usar `['COLUMNA']` y `[['COLUMNA']]` es que en la primera nos va a pasar una *serie*, algo muy parecido a una lista o un arreglo. Mientras que en el segundo formato vamos a pasar un data frame, que incluye la columna y los registros.

In [16]:
# Vamos a traer las 5 primeras computadoras con sus precios
first_laptops_status = laptops_df.head(5)[['brand', 'price']]

first_laptops_status

    brand    price
0   Apple   949.00
1   Apple  1449.00
2  Lenovo  2004.89
3      LG  1486.99
4    acer   949.99

In [17]:
# Vamos a traer todas las ventas y el estatus

all_laptops_price = laptops_df[['brand', 'price']]

all_laptops_price

         brand    price
0        Apple   949.00
1        Apple  1449.00
2       Lenovo  2004.89
3           LG  1486.99
4         acer   949.99
..         ...      ...
609     Lenovo  3799.00
610       acer  1349.00
611  Microsoft  1049.99
612       NIMO   949.98
613       ASUS  2699.99

[614 rows x 2 columns]

3. Limpieza Básica: Renombrar al menos dos columnas y manejar valores nulos (ya sea eliminándolos o llenándolos).

In [18]:
laptops_df['list_price'] = laptops_df['list_price'].fillna(0.0)
laptops_df['stars'] = laptops_df['stars'].fillna(0.0)
laptops_df['description'] = laptops_df['description'].fillna("sin descripción")

# Verificar los cambios
laptops_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           614 non-null    object
 1   brand           614 non-null    object
 2   price           614 non-null    float64
 3   list_price      614 non-null    float64
 4   discount_pct    614 non-null    float64
 5   price_currency  614 non-null    object
 6   stars           614 non-null    float64
 7   reviews_count   614 non-null    int64
 8   breadCrumbs     602 non-null    object
 9   description     614 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 48.1+ KB

In [19]:
laptops_df = laptops_df.rename(columns={'discount_pct': 'discount_percentage', 'breadCrumbs': 'location'})

# Verificar los cambios mostrando las primeras filas y los nombres de las columnas
display(laptops_df.head())
display(laptops_df.columns)

,title,brand,price,list_price,discount_percentage,price_currency,stars,reviews_count,location,description
0,Apple 2025 MacBook Air 13-inch Laptop with M4 ...,Apple,949.00,999.00,5.01,$,4.8,5991,NaN,sin descripción
1,Apple 2025 MacBook Pro Laptop with M5 chip wit...,Apple,1449.00,1599.00,9.38,$,4.7,1217,NaN,sin descripción
2,Lenovo Legion Pro 7i â AI-Powered Gaming Lap...,Lenovo,2004.89,2149.99,6.75,$,4.3,139,Electronics > Computers & Accessories > Comput...,The Lenovo Legion Pro 7i is designed for eSpor...
3,LG 45GX950A-B 45-inch Ultragear 5K2K WUHD (512...,LG,1486.99,1999.99,25.65,$,4.3,323,Electronics > Computers & Accessories > Monitors,Unleash unparalleled gaming prowess with the w...
4,acer Nitro V Gaming Laptop | Intel Core i7-136...,acer,949.99,0.00,0.00,$,4.6,205,Electronics > Computers & Accessories > Comput...,Live For Victory: Elevate your gaming adventur...

Index(['title', 'brand', 'price', 'list_price', 'discount_percentage',
       'price_currency', 'stars', 'reviews_count', 'location', 'description'],
      dtype='object')

Selección y Filtrado: * Crear un nuevo DataFrame que contenga solo 3 columnas específicas.

Filtrar filas basándose en una condición lógica (ej. "Ventas > 1000").

In [20]:
new_laptops_df = laptops_df[['brand', 'price', 'discount_percentage']]
display(new_laptops_df.head())

    brand    price  discount_percentage
0   Apple   949.00                 5.01
1   Apple  1449.00                 9.38
2  Lenovo  2004.89                 6.75
3      LG  1486.99                25.65
4    acer   949.99                 0.00

In [21]:
# Filtramos las laptops con un precio superior a 1200 dólares
high_price_laptops = new_laptops_df[new_laptops_df['price'] > 1200]

high_price_laptops

         brand    price  discount_percentage
1        Apple  1449.00                 9.38
2       Lenovo  2004.89                 6.75
3           LG  1486.99                25.65
5          msi  1888.08                 0.00
6    Alienware  1278.49                 8.68
..         ...      ...                  ...
605     Lenovo  1369.00                 0.00
608       ASUS  1339.00                 0.00
609     Lenovo  3799.00                 0.00
610       acer  1349.00                 0.00
613       ASUS  2699.99                 0.00

[392 rows x 3 columns]

`describe()` en pandas es una herramienta extremadamente útil para obtener un resumen estadístico de los datos de un DataFrame o Serie.

### ¿Qué hace `describe()`?
Proporciona estadísticas descriptivas que resumen la tendencia central, la dispersión y la forma de la distribución de los datos de un DataFrame o Serie.

Por defecto, solo funciona con **columnas numéricas**, aunque también puedes aplicarlo a datos categóricos.

---

### ¿Qué incluye el resumen?
Para datos **numéricos**, incluye:
1. **count**: Número de valores no nulos.
2. **mean**: Media aritmética.
3. **std**: Desviación estándar.
4. **min**: Valor mínimo.
5. **25%**, **50% (mediana)**, **75%**: Cuartiles.
6. **max**: Valor máximo.

Para datos **categóricos** (`include='object'`), incluye:
1. **count**: Número de valores no nulos.
2. **unique**: Número de valores únicos.
3. **top**: Valor más frecuente (moda).
4. **freq**: Frecuencia del valor más frecuente.

In [22]:
new_laptops_df.describe()

             price  discount_percentage
count   614.000000           614.000000
mean   1651.402948             3.306938
std     778.558320             8.527061
min     778.000000             0.000000
25%    1034.742500             0.000000
50%    1448.995000             0.000000
75%    2003.665000             0.000000
max    5859.000000            44.800000

In [23]:
new_laptops_df.describe(include="object")

         brand
count      614
unique      39
top     Lenovo
freq       150

In [24]:
# Calcular el precio promedio por marca
average_prices_by_brand = new_laptops_df.groupby('brand')['price'].mean().sort_values()

# Mostrar las marcas con los precios promedio más bajos (por ejemplo, las 5 más baratas)
display(average_prices_by_brand.head())

brand
SAGAWHALE     879.990000
jumper        964.990000
Beelink       969.000000
INNOCN        999.990000
NIMO         1002.294615
Name: price, dtype: float64

In [25]:
# Seleccionar las marcas más baratas (por ejemplo, las 5 primeras de la lista ordenada)
cheapest_brands = average_prices_by_brand.head(5).index.tolist()

# Filtrar el DataFrame original para incluir solo estas marcas
cheapest_laptops_df = new_laptops_df[new_laptops_df['brand'].isin(cheapest_brands)]

display(cheapest_laptops_df.head())

         brand    price  discount_percentage
50      INNOCN   999.99                  0.0
59        NIMO   899.97                 25.0
125       NIMO   999.99                  0.0
149       NIMO  1299.99                  0.0
194  SAGAWHALE   879.99                  0.0

In [26]:
# Cuantos valores únicos tiene breadCrumbs

new_laptops_df["brand"].unique()

array(['Apple', 'Lenovo', 'LG', 'acer', 'msi', 'Alienware', 'Samsung',
       'Microsoft', 'ASUS', 'Dell', 'KAIGERR', 'HP', 'GMKtec',
       'Thunderobot', 'ist computers', 'INNOCN', 'NIMO', 'MSI',
       'Oemgenuine', 'PCONLINE', 'MALLRACE', 'GIGABYTE', 'GEEKOM',
       'Skytech Gaming', 'Razer', 'SAGAWHALE', 'Thermaltake', 'FIREBAT',
       'Basrdis', 'KOOFORWAY', 'jumper', 'EXCaliberPC', 'GPD',
       'HIDevolution', 'Beelink', 'MKY ITECH', 'ACEMAGIC', 'CyberpowerPC',
       'ME2 MichaelElectronics2'], dtype=object)

Uso de min() y max()
1. min():
* Encuentra el valor más pequeño en los datos.
2. max():
* Encuentra el valor más grande en los datos.
Ambos métodos pueden aplicarse a datos numéricos y categóricos.

In [28]:
# Operamos sobre max y min de descuento

min_discount = new_laptops_df["discount_percentage"].min()
max_discount = new_laptops_df["discount_percentage"].max()

print("Descuento mínimo", min_discount)
print("Descuento máximo:", max_discount)

Descuento mínimo 0.0
Descuento máximo: 44.8