<a href="https://colab.research.google.com/github/KarlyHdzC/Mineria_de_datos/blob/main/Miner%C3%ADa_de_Datos_05_Pandas_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de Datos - Universidad Anáhuac
## Introducción a Python - Libreta 5
**Profesor: Dr. Farid Krayem Pineda**

# Introducción a pandas

## Qué es pandas
Pandas es una biblioteca de Python diseñada para trabajar con datos tabulares de manera eficiente y fácil.

Es ampliamente utilizada en ciencia de datos, análisis de datos y aprendizaje automático.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# Importar pandas
import pandas as pd

In [12]:
# Crear un DataFrame básico
print("\n### Crear un DataFrame desde un diccionario ###")
datos = {
    "Nombre": ["Ana", "Carlos", "Luis", "María"], #serie
    "Edad": [23, 34, 45, 29],
    "Ciudad": ["México", "Guadalajara", "Monterrey", "Puebla"],
    "Genero": ["F", "M", "M", "F"],
    "Altura": [165, 170, 175, 160]
}

df = pd.DataFrame(datos)
print(df)

### Crear un DataFrame desde un diccionario ###
   Nombre  Edad       Ciudad Genero  Altura
0     Ana    23       México      F     165
1  Carlos    34  Guadalajara      M     170
2    Luis    45    Monterrey      M     175
3   María    29       Puebla      F     160

In [7]:
#Imprimir solo lo que tiene Ana o Luis
df_filtrado = df[df['Nombre'].isin(['Ana', 'Luis'])]
print(df_filtrado)

  Nombre  Edad     Ciudad Genero
0    Ana    23     México      F
2   Luis    45  Monterrey      M

In [9]:
df

   Nombre  Edad       Ciudad Genero
0     Ana    23       México      F
1  Carlos    34  Guadalajara      M
2    Luis    45    Monterrey      M
3   María    29       Puebla      F

In [8]:
type(df)

pandas.core.frame.DataFrame

In [13]:
# imprimir el data frame en formato de tabla
df

   Nombre  Edad       Ciudad Genero  Altura
0     Ana    23       México      F     165
1  Carlos    34  Guadalajara      M     170
2    Luis    45    Monterrey      M     175
3   María    29       Puebla      F     160

In [14]:
df.dtypes

Nombre    object
Edad       int64
Ciudad    object
Genero    object
Altura     int64
dtype: object

In [17]:
print(df['Nombre'][0])

Ana

In [19]:
from numpy import dtype
nombre_ana = df['Nombre'][0]
print(nombre_ana)
type(nombre_ana)

Ana

str

In [21]:
df.columns

Index(['Nombre', 'Edad', 'Ciudad', 'Genero', 'Altura'], dtype='object')

In [23]:
# Selección de columnas
print("\n### Seleccionar una columna ###")
print(df["Nombre"])
print(df["Ciudad"][1])

### Seleccionar una columna ###
0       Ana
1    Carlos
2      Luis
3     María
Name: Nombre, dtype: object
Guadalajara

In [27]:
def saludar_persona(num):
  saludar = "¡Hola " + df['Nombre'][num] + "!"
  return saludar

In [28]:
saludar_persona(2)

'¡Hola Luis!'

In [29]:
df["Nombre"]

0       Ana
1    Carlos
2      Luis
3     María
Name: Nombre, dtype: object

In [30]:
# Filtrar datos
print("\n### Filtrar filas (Edad > 30) ###")
print(df[df["Edad"] > 30])

### Filtrar filas (Edad > 30) ###
   Nombre  Edad       Ciudad Genero  Altura
1  Carlos    34  Guadalajara      M     170
2    Luis    45    Monterrey      M     175

In [31]:
treintones = df[df["Edad"] > 30]
treintones

   Nombre  Edad       Ciudad Genero  Altura
1  Carlos    34  Guadalajara      M     170
2    Luis    45    Monterrey      M     175

In [32]:
type(treintones)

pandas.core.frame.DataFrame

In [33]:
# Agregar una nueva columna
print("\n### Agregar una nueva columna ###")
df["Salario"] = [30000, 45000, 50000, 40000]
df

### Agregar una nueva columna ###

   Nombre  Edad       Ciudad Genero  Altura  Salario
0     Ana    23       México      F     165    30000
1  Carlos    34  Guadalajara      M     170    45000
2    Luis    45    Monterrey      M     175    50000
3   María    29       Puebla      F     160    40000

In [34]:
# Agrupar datos
print("\n### Agrupar datos por Ciudad ###")
grouped = df.groupby("Ciudad")["Salario"].mean()
grouped

### Agrupar datos por Ciudad ###

Ciudad
Guadalajara    45000.0
Monterrey      50000.0
México         30000.0
Puebla         40000.0
Name: Salario, dtype: float64

# Trabajando con archivos CSV

In [35]:
# Montamos Google Drive para acceder a los archivos almancenados en la unidad

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [36]:
# Guardamos el archivo dentro de un dataframe de Pandas

file_path = "/content/drive/MyDrive/Colab Notebooks/Mineria de datos/sales_data_sample.csv"

sales_df = pd.read_csv(file_path, encoding='latin1', delimiter=',')

In [37]:
# Muestra los primeros 5 registros por defecto
# aunque se le puede pasar un valor a head()

sales_df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [38]:
# Ahora vamos a ver todas las columnas en el DF

sales_df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')

In [39]:
# Mostramos la estructura del DF en (filas, columnas)

sales_df.shape

(2823, 25)

In [40]:
sales_df.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
ADDRESSLINE2         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
TERRITORY            object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

In [41]:
# Los datos tipo object contienen números y letras
# esto no es de Pyhton, es de Pandas.

sales_df['PRODUCTCODE']

0       S10_1678
1       S10_1678
2       S10_1678
3       S10_1678
4       S10_1678
          ...
2818    S72_3212
2819    S72_3212
2820    S72_3212
2821    S72_3212
2822    S72_3212
Name: PRODUCTCODE, Length: 2823, dtype: object

In [42]:
# Vamos a mostrar los últimos 3 registros
# Para ello usaremos tail()

sales_df.tail(3)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [43]:
# Ahora vamos a mostrar solo los últimos 3 registros de ventas

last_sales = sales_df.tail(3)['SALES']

last_sales

2820    5417.57
2821    2116.16
2822    3079.44
Name: SALES, dtype: float64

In [44]:
# Aquí se mantiene el index de la tabla original
# La tabla original está en sales_df

print(last_sales)

2820    5417.57
2821    2116.16
2822    3079.44
Name: SALES, dtype: float64

In [45]:
# Vamos a resetear el index de este data_frame para evitar errores
# Esto si queremos despues iterar sobre este data_frame

last_sales = last_sales.reset_index(drop=True)

print(last_sales)

0    5417.57
1    2116.16
2    3079.44
Name: SALES, dtype: float64

In [46]:
# Veamos la estructura de last_sales

last_sales.shape # Ojo, no tenemos columna

(3,)

In [47]:
last_sales = sales_df.tail(3)[['SALES']]
last_sales = last_sales.reset_index(drop=True)
last_sales.shape

(3, 1)

La diferencia entre usar `['COLUMNA']` y `[['COLUMNA']]` es que en la primera nos va a pasar una *serie*, algo muy parecido a una lista o un arreglo. Mientras que en el segundo formato vamos a pasar un data frame, que incluye la columna y los registros.

In [48]:
# Vamos a traer las 5 primeras ventas con su estatus
first_sales_status = sales_df.head(5)[['SALES', 'STATUS']]

first_sales_status

     SALES   STATUS
0  2871.00  Shipped
1  2765.90  Shipped
2  3884.34  Shipped
3  3746.70  Shipped
4  5205.27  Shipped

In [49]:
# Vamos a traer todas las ventas y el estatus

all_sales_status = sales_df[['SALES', 'STATUS']]

all_sales_status

        SALES    STATUS
0     2871.00   Shipped
1     2765.90   Shipped
2     3884.34   Shipped
3     3746.70   Shipped
4     5205.27   Shipped
...       ...       ...
2818  2244.40   Shipped
2819  3978.51   Shipped
2820  5417.57  Resolved
2821  2116.16   Shipped
2822  3079.44   On Hold

[2823 rows x 2 columns]

In [50]:
# Ahora solo las ventas que están "On Hold"

on_hold_sales = sales_df[sales_df['STATUS'] == 'On Hold'][['SALES', 'STATUS', 'CITY']]

on_hold_sales = on_hold_sales.reset_index(drop=True)

on_hold_sales

       SALES   STATUS      CITY
0    2764.88  On Hold    Boston
1    3188.12  On Hold      Lule
2    7048.14  On Hold  San Jose
3   14082.80  On Hold  San Jose
4    3051.30  On Hold  San Jose
5    5814.86  On Hold      Lule
6    2086.92  On Hold      Lule
7    3193.26  On Hold    Newark
8    6386.16  On Hold  San Jose
9    3255.12  On Hold    Boston
10   4872.03  On Hold    Boston
11   2878.80  On Hold      Lule
12   5808.48  On Hold    Boston
13    541.14  On Hold  San Jose
14   1207.68  On Hold    Boston
15   6763.47  On Hold      Lule
16   4421.34  On Hold  San Jose
17   1987.18  On Hold  San Jose
18   2576.00  On Hold  San Jose
19   3659.02  On Hold    Newark
20   3335.23  On Hold    Boston
21   5528.04  On Hold      Lule
22   7182.00  On Hold  San Jose
23   5820.35  On Hold  San Jose
24   6107.40  On Hold    Boston
25   1057.29  On Hold  San Jose
26   3729.39  On Hold  San Jose
27   3891.81  On Hold    Boston
28   3843.20  On Hold    Newark
29   4219.28  On Hold    Newark
30   4992.61  On Hold    Newark
31   4819.26  On Hold    Newark
32   1979.60  On Hold    Newark
33   2639.58  On Hold    Boston
34   1135.31  On Hold    Newark
35   3533.62  On Hold    Boston
36   7543.75  On Hold    Newark
37   2352.59  On Hold    Boston
38   2018.31  On Hold    Newark
39   7084.00  On Hold    Newark
40   3029.04  On Hold    Boston
41   2439.99  On Hold    Boston
42   2031.40  On Hold    Newark
43   3079.44  On Hold    Boston

`describe()` en pandas es una herramienta extremadamente útil para obtener un resumen estadístico de los datos de un DataFrame o Serie.

### ¿Qué hace `describe()`?
Proporciona estadísticas descriptivas que resumen la tendencia central, la dispersión y la forma de la distribución de los datos de un DataFrame o Serie.

Por defecto, solo funciona con **columnas numéricas**, aunque también puedes aplicarlo a datos categóricos.

---

### ¿Qué incluye el resumen?
Para datos **numéricos**, incluye:
1. **count**: Número de valores no nulos.
2. **mean**: Media aritmética.
3. **std**: Desviación estándar.
4. **min**: Valor mínimo.
5. **25%**, **50% (mediana)**, **75%**: Cuartiles.
6. **max**: Valor máximo.

Para datos **categóricos** (`include='object'`), incluye:
1. **count**: Número de valores no nulos.
2. **unique**: Número de valores únicos.
3. **top**: Valor más frecuente (moda).
4. **freq**: Frecuencia del valor más frecuente.

In [51]:
sales_df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [52]:
sales_df.describe(include="object")

,ORDERDATE,STATUS,PRODUCTLINE,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
count,2823,2823,2823,2823,2823,2823,2823,302,2823,1337,2747,2823,1749,2823,2823,2823
unique,252,6,7,109,92,91,92,9,73,16,73,19,3,77,72,3
top,11/14/2003 0:00,Shipped,Classic Cars,S18_3232,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Level 3,Madrid,CA,28034,USA,EMEA,Freyre,Diego,Medium
freq,38,2617,967,52,259,259,259,55,304,416,259,1004,1407,259,259,1384

In [53]:
# Filtrar los que han sido enviados

enviados_df = sales_df[sales_df['STATUS'].isin(['Shipped', 'In Process'])]

enviados_df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2815,10315,40,55.69,5,2227.60,10/29/2004 0:00,Shipped,4,10,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small

In [54]:
# Cuantos valores únicos tiene STATUS

enviados_df["STATUS"].unique()

array(['Shipped', 'In Process'], dtype=object)

In [55]:
# Contamos cuantos elementos Shipped existen

(enviados_df["STATUS"] == "Shipped").sum()

np.int64(2617)

Uso de min() y max()
1. min():
* Encuentra el valor más pequeño en los datos.
2. max():
* Encuentra el valor más grande en los datos.
Ambos métodos pueden aplicarse a datos numéricos y categóricos.

In [56]:
# Operamos sobre max y min

min_sales = sales_df["SALES"].min()
max_sales = sales_df["SALES"].max()

print("Ventas mínimas:", min_sales)
print("Ventas máximas:", max_sales)

Ventas mínimas: 482.13
Ventas máximas: 14082.8